title: 3GPP CHF CDR Decoder
description: A Web front to charging function record ASN.1 BER CDR to JSON decoder in development.
theme: just-the-docs

url: https://li-hao-.github.io

aux_links:
  GitHub Site: https://github.com/li-hao-/
